#@data/values
---
appName: dashboard-api
namespace: dashboard-api
containerPort: 8080
imageName: dashboard-api
ingressHost: dashboard.api.127.0.0.1.nip.io
healthCheckPath: /api/v1/health
env: 
- name: DATABASE_HOSTNAME
  value: dashboard-database-svc
- name: DATABASE_PORT
  value: "5432"
- name: DATABASE_NAME
  value: mcmsdb
- name: DATABASE_USER
  value: mcmsuser
- name: DATABASE_PASSWORD
  value: mcmsuser123!
- name: FRONTEND_HOSTNAME
  value: dashboard.web.127.0.0.1.nip.io
- name: FRONTEND_PORT
  value: "8443"
